-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AUTO_PARK_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AUTO_PARK_DB` ;

-- -----------------------------------------------------
-- Schema AUTO_PARK_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AUTO_PARK_DB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `AUTO_PARK_DB` ;

-- -----------------------------------------------------
-- Table `AUTO_PARK_DB`.`TB_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AUTO_PARK_DB`.`TB_USER` ;

CREATE TABLE IF NOT EXISTS `AUTO_PARK_DB`.`TB_USER` (
  `ID_USER` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NA_NAME_USER` VARCHAR(50) NOT NULL COMMENT '',
  `TB_USERcol` VARCHAR(45) NOT NULL COMMENT '',
  `FN_FULL_NAME_USER` VARCHAR(150) NOT NULL COMMENT '',
  `EA_EMAIL_ADRESS_USER` VARCHAR(200) NOT NULL COMMENT '',
  `PW_PASSWORD_USER` VARCHAR(50) NOT NULL COMMENT '',
  `PH_PHONE_USER` VARCHAR(13) NOT NULL COMMENT '',
  `ST_STATUS_USER` INT NOT NULL COMMENT '',
  `CO_FALLOWEDBY` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ID_USER`)  COMMENT '',
  INDEX `ID_USER` (`CO_FALLOWEDBY` ASC)  COMMENT '',
  CONSTRAINT `CO_FALLOWEDBY`
    FOREIGN KEY (`CO_FALLOWEDBY`)
    REFERENCES `AUTO_PARK_DB`.`TB_USER` (`ID_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AUTO_PARK_DB`.`TB_ESTABLISHMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AUTO_PARK_DB`.`TB_ESTABLISHMENT` ;

CREATE TABLE IF NOT EXISTS `AUTO_PARK_DB`.`TB_ESTABLISHMENT` (
  `ID_ESTABLISHMENT` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NA_NAME_ESTABLISHMENT` VARCHAR(50) NOT NULL COMMENT '',
  `EA_ESTABLISHMENT_ADRESS` VARCHAR(150) NOT NULL COMMENT '',
  `TV_VACANCIES` INT NOT NULL COMMENT '',
  `LO_LONGITUDE` VARCHAR(100) NOT NULL COMMENT '',
  `LA_LATITUDE` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`ID_ESTABLISHMENT`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AUTO_PARK_DB`.`TB_CLASSIFICATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AUTO_PARK_DB`.`TB_CLASSIFICATION` ;

CREATE TABLE IF NOT EXISTS `AUTO_PARK_DB`.`TB_CLASSIFICATION` (
  `ID_CLASSIFICATION` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `DH_REGISTRY_TIME` DATETIME(6) NOT NULL COMMENT '',
  `ST_STABLISHMENT_STARS` INT NOT NULL COMMENT '',
  `CO_USER_ID` INT NOT NULL COMMENT '',
  `CO_ESTABLISHMENT_ID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ID_CLASSIFICATION`)  COMMENT '',
  INDEX `ID_USER` (`CO_USER_ID` ASC)  COMMENT '',
  INDEX `ID_ESTABLISHMENT` (`CO_ESTABLISHMENT_ID` ASC)  COMMENT '',
  CONSTRAINT `CO_USER_ID`
    FOREIGN KEY (`CO_USER_ID`)
    REFERENCES `AUTO_PARK_DB`.`TB_USER` (`ID_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CO_ESTABLISHMENT_ID`
    FOREIGN KEY (`CO_ESTABLISHMENT_ID`)
    REFERENCES `AUTO_PARK_DB`.`TB_ESTABLISHMENT` (`ID_ESTABLISHMENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
